import type { Metadata } from "next";
import { siteText, site } from "../content/site";
import { defaultLocale, localeFormats, locales, localizePath, type Locale } from "../i18n/locales";

interface PageMetadataInput {
  locale: Locale;
  title: string;
  description: string;
  // The English path; the French one is derived from it.
  path: string;
  type?: "website" | "article";
}

// The same page in every language, for search engines (hreflang). x-default is English.
export function languageAlternates(path: string): Record<string, string> {
  return {
    ...Object.fromEntries(locales.map((locale) => [locale, localizePath(locale, path)])),
    "x-default": localizePath(defaultLocale, path),
  };
}

// Next.js replaces a parent's openGraph and twitter objects instead of merging them,
// so every page builds the complete set here.
export function pageMetadata({ locale, title, description, path, type = "website" }: PageMetadataInput): Metadata {
  // The share image generated by app/opengraph-image.tsx.
  const image = { url: "/opengraph-image", width: 1200, height: 630, alt: siteText[locale].title };
  const url = localizePath(locale, path);

  return {
    title,
    description,
    alternates: { canonical: url, languages: languageAlternates(path) },
    openGraph: {
      type,
      siteName: site.name,
      locale: localeFormats[locale].openGraph,
      url,
      title,
      description,
      images: [image],
    },
    twitter: { card: "summary_large_image", title, description, images: [image] },
  };
}
