import type { Metadata } from "next";
import { site } from "../content/site";

// The share image generated by app/opengraph-image.tsx.
const SHARE_IMAGE = { url: "/opengraph-image", width: 1200, height: 630, alt: site.title };

interface PageMetadataInput {
  title: string;
  description: string;
  path: string;
  type?: "website" | "article";
}

// Next.js replaces a parent's openGraph and twitter objects instead of merging them,
// so every page builds the complete set here.
export function pageMetadata({ title, description, path, type = "website" }: PageMetadataInput): Metadata {
  return {
    title,
    description,
    alternates: { canonical: path },
    openGraph: {
      type,
      siteName: site.name,
      locale: "en_GB",
      url: path,
      title,
      description,
      images: [SHARE_IMAGE],
    },
    twitter: { card: "summary_large_image", title, description, images: [SHARE_IMAGE] },
  };
}
